### ISSUE TITLE
Write a GraphQL resolver that obtains AminoAcid-Sequences from NCBI

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/dotfiles#10]
Proteins are chains of amino acids. There are 20(21) amino acids. Hence a protein can be expressed as a text using an alphabet of 21 letters. 
The US based National Center for Biotechnology Information (NCBI) among many other things has a very large database of such sequences. Luckily there is a REST-endpoint to obtain these sequences in the common [FASTA format](en.wikipedia.org/wiki/FASTA_format). The endpoint is fully defined with the following example:
````
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NP_005537.3&rettype=fasta&retmode=text
````
For a documentation of NCBI's Api see [here](https://www.ncbi.nlm.nih.gov/books/NBK25500/)
For more information on proteins and amino-acid sequences see [Wikipedia](https://en.wikipedia.org/wiki/Protein)

The task is to write a GraphQL resolver using NodeJS that accepts a GraphQL request containing the protein's [_accession_](https://en.wikipedia.org/wiki/Accession_number_(bioinformatics)).

Basic methodology should be clear by now:
1. Generate a NodeJS object with a resolve function for GraphQL
2. Receive and parse the GraphQL request, obtaining the [_accession_](https://en.wikipedia.org/wiki/Accession_number_(bioinformatics))
3. Launch a request to the NCBI server, and parse the `FASTA` to an object of the following format:
````{ accession: xyz; sequence: the_amino_acid_seq}````

**Comment by mariotorres** [comment]
https://github.com/mariotorres/ncbi_graphql_server

**Comment by asishallab** [comment]
Above code from @mariotorres resolves the issue nicely. Thank you!
